## Plot 3: Engery Sub Metering Over DateTime.                                                                                                                                                                                               
                                                                                                                                                                                                                                            
## Download the archived data file from https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip.                                                                                                              
## and extract it in the root of the project directory. Once done you'll end up with a raw data file named household_power_consumption.txt.                                                                                                 
                                                                                                                                                                                                                                            
## Load the data into R.                                                                                                                                                                                                                    
d <- read.csv("household_power_consumption.txt", sep=";", header=TRUE, colClasses=c("character","character","numeric",NA,NA,NA,NA,NA,NA), na.strings="?")                                                                                   
                                                                                                                                                                                                                                            
## Filter out the data for 2007/02/01 and 2007/0202.                                                                                                                                                                                        
d <- d[d$Date == "1/2/2007" | d$Date == "2/2/2007",]                                                                                                                                                                                        
                                                                                                                                                                                                                                            
## Create a new DateTime column that combines the Date and Time columns into a date/time stamp.                                                                                                                                             
d$DateTime <- with(d, as.POSIXct(paste(Date, Time) , format = "%e/%m/%Y %H:%M:%S"))                                                                                                                                                         
                                                                                                                                                                                                                                            
## Open the png device and point it to our file we wnt on disk.                                                                                                                                                                             
png(file="plot3.png")                                                                                                                                                                                                                       
                                                                                                                                                                                                                                            
## Plot a line chart of the Global Active Power over DateTimWrite failed: Broken pipe                                                                                                                                                       
with(d, plot(Sub_metering_1 ~ DateTime, xlab="", ylab="Energy sub metering", type="l"))
with(d, lines(Sub_metering_2 ~ DateTime, col="red"))
with(d, lines(Sub_metering_3 ~ DateTime, col="blue"))
legend("topright", lwd=1, pch=c(NA, NA, NA), col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), merge=FALSE)
                                                                                                                                                                                                                                            
## Close the graphics device to write the PNG data to file.                                                                                                                                                                                 
dev.off()                                                                                                                                                                                                                                   
